spring:
  application:
    name: batch-api

  profiles:
    active: dev

  batch:
    job:
      enabled: false

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

server:
  port: 9090
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 3
    max-total: 5
    max-idle: 3
    min-idle: 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: ALWAYS

api:
  gateway:
    host: localhost
    port: 8080

eureka:
  instance:
    instance-id: batch-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

schedule:
  expire:
    coupon:
      cron: 0/10 * * * * ?
  birthday:
    coupon:
      cron: 0/15 * * * * ?

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    mysql:
      url: d5dd1aea7a81489e8b2b2d3a650c0a4e
      username: 6764281f095b4154ab34a04b4fea6b8d
      password: 3a23273e707b438e94f104f47ce7a7ba

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 3
    max-total: 5
    max-idle: 3
    min-idle: 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: ALWAYS

api:
  gateway:
    host: buzz-book.store
    port: 8080

eureka:
  instance:
    instance-id: batch-api
    hostname: eureka-server
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka

schedule:
  expire:
    coupon:
      cron: 0 0/5 * * * ?
  birthday:
    coupon:
      cron: 0 0/5 * * * ?

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    mysql:
      url: 0e5015e36f91453d806dbd77ba595347
      username: 0f85ac52219545d382eab76db989e848
      password: 54e01f8caa504a6ca5e69d30e66bf348