spring:
  application:
    name: batch

  profiles:
    active: dev

  batch:
    job:
      enabled: true
      name: expireCouponJob

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_aa_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: be6_aa
    password: 6@H(77fpCZDiC6!!
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 5
    max-total: 10
    max-idle: 5
    min-idle: 3

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: ALWAYS